[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace.dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "process", "io-util", "io-std", "sync", "time", "fs", "macros"] }
axum = "0.8"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
lsp-types = "0.97"
async-trait = "0.1"
thiserror = "2"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
reqwest = { version = "0.12", default-features = false, features = ["blocking", "rustls-tls", "json"] }
toml = "0.8"
sha2 = "0.10"
zip = "2"
flate2 = "1"
tempfile = "3"
ignore = "0.4"
regex = "1"
win32job = "2"
dunce = "1"
windows-sys = { version = "0.59", features = ["Win32_System_Console"] }
bytes = "1"

[workspace.lints.clippy]
all = { level = "deny" }
